### ISSUE TITLE
Could not resolve react import in Apollo dependency

### ISSUE THREAD

**Issue by VanderschuerenMaximilian** [VanderschuerenMaximilian/Jaron-Maximilian#14]
## Wat loopt er fout?
Bij het runnen van de pwa folder krijg ik een error dat een import voor react in de Apollo dependency.

## Waar situeert het probleem zich (beiden aanduiden kan)?
- [x] Frontend
- [ ] Backend

## Wat heb je zelf opgezocht? / Wat heeft je team-genoot geprobeerd?
- Code die het probleem kan veroorzaken in commentaar gezet (views/Alerts.vue)
- Node modules verwijderd en opnieuw gedownload
- import & dependency gecheckt

## Hoe kan het probleem gereproduceerd worden op jullie repo?
De pwa folder runnen op de branch: feature/employee-and-alerts-on-dashboard

## Waar staat de code die relevant is (gebruik een permalink)?

https://github.com/VanderschuerenMaximilian/Jaron-Maximilian/blob/feature/employee-and-alerts-on-dashboard/packages/pwa/src/views/Alerts.vue

**Comment by MLoth** [comment]
Probeer eens met de manual installation: `npm install --save graphql graphql-tag @apollo/client`.

**Comment by MLoth** [comment]
Aha! Ik denk dat je een verkeerde import hebt in `alert.mutation.ts`. Je doet een import van de verkeerde package. Dit zal wel kunnen werken, maar dan moet je nog naar /core gaan of zo.

Anyway, ik zou aanraden:
❌ `import { gql } from '@apollo/client'` weg en
✅ `import gql from 'graphql-tag';` in de plaats.

(Niet getest, maar dat zal wel werken 🙂.)
